name = "doom"
compatibility_date = "2023-06-02"
# main = "site/index.js"

account_id = ""
workers_dev = false
routes = [
	# Change to the route and zone you want to deploy the Worker on
	{ pattern = "doom.example.com/*", zone_name = "example.com" }
]

webpack_config = "site/webpack.js"

[site]
bucket = "./assets"
entry-point = "site"

[build]
command = "npm install"
watch_dir="./site"

